### PR TITLE
maint: stop ignoring q2-assembly

### PR DESCRIPTION
**Pull request by thermokarst**

### CODE REVIEW

**Comment by thermokarst** [comment]
```
package q2-diversity-lib-2022.4.0.dev0+3.g6347cff-py38_0 requires python_abi 3.8.* *_cp38, but none of the providers can be installed
```

It's a shame that this resolution error is so opaque, but I suspect we've got some direct dependency conflicts - @misialq, any thoughts?

**Comment by thermokarst** [comment]
No those are unrelated - I'm bumping everything to skbio 0.5.7 right now, so there will be some failures until all the impacted packages are rebuilt.

**Comment by misialq** [comment]
Sorry @thermokarst, I have know clue what's going on here. What would be the easiest way to get the full package list that should be resolved here? I've been trying to reproduce that locally but it's a bit difficult to find out what exactly is being used to solve the environment...

**Comment by thermokarst** [comment]
Hey @misialq! Looks like yesterday's major dependency refresh sorted things out. The recipe that is being built for the conda metapackage can be found in the `debug recipe` step of the github workflow:

https://github.com/qiime2/package-integration/runs/7008290885?check_suite_focus=true#step%253A6%253A11

**Pull request merged**
