### PR TITLE
IMP: adds jupyter notebook to the meta.yaml.jinja file

### PR DESCRIPTION
**Pull request by cherman2**
This PR adds notebook to the Meta.yaml.jinja file so that notebook is always installed with qiime2.

### CODE REVIEW

**Comment by cherman2** [comment]
I dont know if I did this right. 

Also I dont really know the process for the projects so I did not add this to the project board.

**Comment by cherman2** [comment]
I am trying to reference this file for the 2022.2 release: https://github.com/qiime2/package-integration/blob/main/2022.2/staged/core/meta.yaml.jinja

**Comment by ebolyen** [comment]
Hey @cherman2, I think you actually have it right!

If we look at the log, we see we're missing a token to communicate with the library, but your build worked fine otherwise ([see this line](https://github.com/qiime2/package-integration/actions/runs/3298520295/jobs/5440748931#step:7:282)).

The reason for this is forked repositories don't have access to secrets in the repository (it would be easy to write a PR that just dumped all of your secrets or sent them to some nefarious website), so your PR isn't allowed to communicate with our server. This is normal and we usually create PRs off of the "upstream" repo instead of our own forks _for this particular repo_ to avoid that.

In terms of content, I would drop the version requirement and just have conda solve whatever is going to make sense. (And maybe add this same line to the community distro as well)

**Comment by lizgehret** [comment]
Hey @cherman2 - I can't remember where we left off on this one. I don't see a new pull request for this one from the canonical repo - do you want to do that? I'm also happy to do it, just let me know what you'd prefer - then we can close this one out!

**Comment by cherman2** [comment]
@lizgehret, 
I can not push to the canonical repo, I have not earned that 😝 . Also My pull request failed because I pushed the change to the community and core distro at the same time which is a NO NO apparently.  I asked @ebolyen what I should do and he said that y'all would take it from here. Happy to do whatever is helpful but that's where it was left off.

**Comment by lizgehret** [comment]
Gotcha, I remember that now - thanks @cherman2! I'll get this sorted and cut two new PRs for core/community. Thanks for getting the ball rolling on this! 😄

**Comment by lizgehret** [comment]
New PRs linked here:

[Core](https://github.com/qiime2/package-integration/pull/375)
[Community](https://github.com/qiime2/package-integration/pull/374)

**Pull request closed without merging**
